'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Printer, Download } from 'lucide-react';

interface ReceiptData {
  memberName: string;
  memberPhone: string;
  schemeName: string;
  schemeType: string;
  grossAmount: number;
  serviceCharge: number;
  netPayout: number;
  processedAt: string;
  receiptNumber: string;
}

interface ReceiptGeneratorProps {
  receiptData: ReceiptData;
}

export function ReceiptGenerator({ receiptData }: ReceiptGeneratorProps) {
  const [isGenerating, setIsGenerating] = useState(false);

  const handlePrint = () => {
    window.print();
  };

  const generateReceiptHTML = () => {
    return `
    <!DOCTYPE html>
    <html>
    <head>
        <title>Adashi Receipt - ${receiptData.receiptNumber}</title>
        <style>
            body { font-family: Arial, sans-serif; max-width: 400px; margin: 0 auto; padding: 20px; }
            .header { text-align: center; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; }
            .receipt-title { font-size: 24px; font-weight: bold; margin-bottom: 5px; }
            .receipt-subtitle { font-size: 14px; color: #666; }
            .section { margin-bottom: 15px; }
            .label { font-weight: bold; display: inline-block; width: 120px; }
            .value { display: inline-block; }
            .amount-row { display: flex; justify-content: space-between; padding: 5px 0; }
            .total-row { display: flex; justify-content: space-between; padding: 10px 0; border-top: 1px solid #000; font-weight: bold; font-size: 18px; }
            .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #666; }
            @media print { body { margin: 0; } }
        </style>
    </head>
    <body>
        <div class="header">
            <div class="receipt-title">ADASHI RECEIPT</div>
            <div class="receipt-subtitle">Digital Savings Manager</div>
        </div>
        
        <div class="section">
            <div><span class="label">Receipt No:</span> <span class="value">${receiptData.receiptNumber}</span></div>
            <div><span class="label">Date:</span> <span class="value">${new Date(receiptData.processedAt).toLocaleDateString()}</span></div>
            <div><span class="label">Time:</span> <span class="value">${new Date(receiptData.processedAt).toLocaleTimeString()}</span></div>
        </div>
        
        <div class="section">
            <div><span class="label">Member:</span> <span class="value">${receiptData.memberName}</span></div>
            <div><span class="label">Phone:</span> <span class="value">${receiptData.memberPhone}</span></div>
            <div><span class="label">Scheme:</span> <span class="value">${receiptData.schemeName}</span></div>
            <div><span class="label">Type:</span> <span class="value">${receiptData.schemeType.toUpperCase()}</span></div>
        </div>
        
        <div class="section">
            <div class="amount-row">
                <span>Total Savings:</span>
                <span>₦${receiptData.grossAmount.toLocaleString()}</span>
            </div>
            ${receiptData.serviceCharge > 0 ? `
            <div class="amount-row">
                <span>Service Charge:</span>
                <span>-₦${receiptData.serviceCharge.toLocaleString()}</span>
            </div>
            ` : ''}
            <div class="total-row">
                <span>Net Payout:</span>
                <span>₦${receiptData.netPayout.toLocaleString()}</span>
            </div>
        </div>
        
        <div class="footer">
            <p>Thank you for saving with us!</p>
            <p>Keep this receipt for your records</p>
            <p>Generated by Adashi Digital Manager</p>
        </div>
    </body>
    </html>
    `;
  };

  const handleDownload = () => {
    setIsGenerating(true);
    try {
      const receiptHTML = generateReceiptHTML();
      const blob = new Blob([receiptHTML], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `receipt-${receiptData.receiptNumber}.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Error generating receipt:', error);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Receipt</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Receipt Preview */}
        <div className="border rounded-lg p-4 bg-white text-black max-w-sm mx-auto">
          <div className="text-center border-b-2 border-black pb-2 mb-4">
            <div className="text-lg font-bold">ADASHI RECEIPT</div>
            <div className="text-xs text-gray-600">Digital Savings Manager</div>
          </div>
          
          <div className="space-y-2 text-sm">
            <div className="flex justify-between">
              <span className="font-semibold">Receipt No:</span>
              <span>{receiptData.receiptNumber}</span>
            </div>
            <div className="flex justify-between">
              <span className="font-semibold">Date:</span>
              <span>{new Date(receiptData.processedAt).toLocaleDateString()}</span>
            </div>
          </div>
          
          <div className="mt-4 space-y-1 text-sm">
            <div><span className="font-semibold">Member:</span> {receiptData.memberName}</div>
            <div><span className="font-semibold">Scheme:</span> {receiptData.schemeName}</div>
          </div>
          
          <div className="mt-4 space-y-1 text-sm">
            <div className="flex justify-between">
              <span>Total Savings:</span>
              <span>₦{receiptData.grossAmount.toLocaleString()}</span>
            </div>
            {receiptData.serviceCharge > 0 && (
              <div className="flex justify-between">
                <span>Service Charge:</span>
                <span>-₦{receiptData.serviceCharge.toLocaleString()}</span>
              </div>
            )}
            <div className="flex justify-between border-t border-black pt-2 font-bold">
              <span>Net Payout:</span>
              <span>₦{receiptData.netPayout.toLocaleString()}</span>
            </div>
          </div>
          
          <div className="mt-4 text-center text-xs text-gray-600">
            <p>Thank you for saving with us!</p>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex gap-2">
          <Button onClick={handlePrint} variant="outline" className="flex-1">
            <Printer className="h-4 w-4 mr-2" />
            Print
          </Button>
          <Button onClick={handleDownload} disabled={isGenerating} className="flex-1">
            <Download className="h-4 w-4 mr-2" />
            {isGenerating ? 'Generating...' : 'Download'}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}